name: Build SMTPE specification

inputs:
  CANONICAL_LINK_PREFIX:
    required: false
  AWS_S3_REGION:
    required: true
  AWS_S3_BUCKET:
    required: true
  AWS_S3_KEY_PREFIX:
    required: true
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
  steps:

    - name: Confirm that the right workflow is active
      shell: bash
      run: cmp ${GITHUB_ACTION_PATH}/../.github/workflows/main.yml .github/workflows/main.yml

    - name: Install vnu
      shell: bash
      run: sudo pip install html5validator==0.4.2

    - name: Install node dependencies
      shell: bash
      run: npm install ${GITHUB_ACTION_PATH}/..

    - name: Build and deploy spec
      shell: bash
      env:
        AWS_S3_REGION: ${{ inputs.AWS_S3_REGION }}
        AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
        AWS_S3_KEY_PREFIX: ${{ inputs.AWS_S3_KEY_PREFIX }}
        CANONICAL_LINK_PREFIX: ${{ inputs.CANONICAL_LINK_PREFIX }}
      run: node ${GITHUB_ACTION_PATH}/../scripts/build.mjs deploy

    - name: Determine which pull request we are on
      uses: jwalton/gh-find-current-pr@v1
      if: github.event_name == 'pull_request'
      id: finder
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}

    - name: Add review links to the pull request
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request' && steps.finder
      with:
        number: ${{ steps.finder.outputs.pr }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        path: ./build/pr-links.md