name: Build SMTPE specification

inputs:
  AWS_S3_REGION:
    required: true
  AWS_S3_BUCKET:
    required: true
  AWS_S3_KEY_PREFIX:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install node dependencies
      env:
        PUPPETEER_PRODUCT: chrome
      shell: bash
      run: |
        npm install puppeteer
        npm install @aws-sdk/client-s3

    - name: Build and deploy spec
      shell: bash
      env:
        AWS_S3_REGION: ${{ inputs.AWS_S3_REGION }}
        AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
        AWS_S3_KEY_PREFIX: ${{ inputs.AWS_S3_KEY_PREFIX }}
      run: node tooling/scripts/build.js